name: Test actions cache
on:
  push: {}
jobs:
  cache_prime_numbers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - run: echo ${ACTIONS_RUNTIME_URL}
      
      - name: Generate cache-key that expires every 60 seconds
        id: gen-cache-key
        run: |
          current_date=$(date +"%s")
          key=$(expr ${current_date} / 60)
          echo "${key}"
          echo "::set-output name=key::${key}"
  
      - name: Cache Primes
        id: cache-primes
        uses: actions/cache@v2
        with:
          path: prime-numbers
          key: ${{ runner.os }}-${{ steps.gen-cache-key.outputs.key}}-primes
  
      - name: Generate Prime Numbers
        if: steps.cache-primes.outputs.cache-hit != 'true'
        run: |
          echo "2 3 5 7 11 13" > prime-numbers
  
      - name: Use Prime Numbers
        run: cat prime-numbers

      - name: Dump github context
        run:   echo "$GITHUB_CONTEXT" | tee context.json
        shell: bash
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: Upload github context
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: context.json

      - name: Dump env
        run: env
